#!/usr/bin/with-contenv bash
set -euo pipefail

OPTIONS="/data/options.json"

CLIENTS_CONF="/etc/freeradius/3.0/clients.conf"
AUTHORIZE_FILE="/etc/freeradius/3.0/mods-config/files/authorize"

enable_mod() {
  local mod="$1"
  if [ -f "/etc/freeradius/3.0/mods-available/${mod}" ] && [ ! -e "/etc/freeradius/3.0/mods-enabled/${mod}" ]; then
    ln -s "/etc/freeradius/3.0/mods-available/${mod}" "/etc/freeradius/3.0/mods-enabled/${mod}"
  fi
}

echo "[FreeRADIUS] Enabling required modules..."
enable_mod "files"
enable_mod "eap"
enable_mod "mschap"

if [ -f "/etc/freeradius/3.0/sites-available/default" ] && [ ! -e "/etc/freeradius/3.0/sites-enabled/default" ]; then
  ln -s "/etc/freeradius/3.0/sites-available/default" "/etc/freeradius/3.0/sites-enabled/default"
fi
if [ -f "/etc/freeradius/3.0/sites-available/inner-tunnel" ] && [ ! -e "/etc/freeradius/3.0/sites-enabled/inner-tunnel" ]; then
  ln -s "/etc/freeradius/3.0/sites-available/inner-tunnel" "/etc/freeradius/3.0/sites-enabled/inner-tunnel"
fi

echo "[FreeRADIUS] Generating clients.conf..."
: > "$CLIENTS_CONF"
echo "### Generated by Home Assistant add-on" >> "$CLIENTS_CONF"

jq -c '.clients[]' "$OPTIONS" | while read -r c; do
  name="$(echo "$c" | jq -r '.name')"
  ipaddr="$(echo "$c" | jq -r '.ipaddr')"
  secret="$(echo "$c" | jq -r '.secret')"

  cat >> "$CLIENTS_CONF" <<EOF

client ${name} {
  ipaddr = ${ipaddr}
  secret = ${secret}
}
EOF
done

echo "[FreeRADIUS] Generating users file (authorize)..."
: > "$AUTHORIZE_FILE"
echo "### Generated by Home Assistant add-on" >> "$AUTHORIZE_FILE"

jq -c '.users[]' "$OPTIONS" | while read -r u; do
  username="$(echo "$u" | jq -r '.username')"
  password="$(echo "$u" | jq -r '.password')"
  echo "${username} Cleartext-Password := \"${password}\"" >> "$AUTHORIZE_FILE"
done

echo "[FreeRADIUS] Starting..."
exec /usr/sbin/radiusd -f -l stdout
