#!/usr/bin/env bash
set -euo pipefail

OPTIONS="/data/options.json"

RDB="/etc/raddb"
CLIENTS_CONF="${RDB}/clients.conf"
AUTHORIZE_FILE="${RDB}/mods-config/files/authorize"

enable_mod() {
  local mod="$1"
  if [ -f "${RDB}/mods-available/${mod}" ] && [ ! -e "${RDB}/mods-enabled/${mod}" ]; then
    ln -s "${RDB}/mods-available/${mod}" "${RDB}/mods-enabled/${mod}"
  fi
}

enable_site() {
  local site="$1"
  if [ -f "${RDB}/sites-available/${site}" ] && [ ! -e "${RDB}/sites-enabled/${site}" ]; then
    ln -s "${RDB}/sites-available/${site}" "${RDB}/sites-enabled/${site}"
  fi
}

echo "[FreeRADIUS] Enabling required modules..."
enable_mod "files"
enable_mod "eap"
enable_mod "mschap"

echo "[FreeRADIUS] Enabling required sites..."
enable_site "default"
enable_site "inner-tunnel"

echo "[FreeRADIUS] Generating clients.conf..."
: > "$CLIENTS_CONF"
echo "### Generated by Home Assistant add-on" >> "$CLIENTS_CONF"

jq -c '.clients[]' "$OPTIONS" | while read -r c; do
  name="$(echo "$c" | jq -r '.name')"
  ipaddr="$(echo "$c" | jq -r '.ipaddr')"
  secret="$(echo "$c" | jq -r '.secret')"

  cat >> "$CLIENTS_CONF" <<EOF

client ${name} {
  ipaddr = ${ipaddr}
  secret = ${secret}
}
EOF
done

echo "[FreeRADIUS] Generating users file (authorize)..."
mkdir -p "$(dirname "$AUTHORIZE_FILE")"
: > "$AUTHORIZE_FILE"
echo "### Generated by Home Assistant add-on" >> "$AUTHORIZE_FILE"

jq -c '.users[]' "$OPTIONS" | while read -r u; do
  username="$(echo "$u" | jq -r '.username')"
  password="$(echo "$u" | jq -r '.password')"
  echo "${username} Cleartext-Password := \"${password}\"" >> "$AUTHORIZE_FILE"
done

echo "[FreeRADIUS] Starting radiusd..."
exec /usr/sbin/radiusd -f -l stdout
